<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Privat24\Module'                             => __DIR__ . '/Module.php',
  'Privat24\Controller\Privat24Controller'      => __DIR__ . '/src/Controller/Privat24Controller.php',
  'Privat24\Exception\ExceptionStrategy'        => __DIR__ . '/src/Exception/ExceptionStrategy.php',
  'Privat24\Form\Prvat24Form'                   => __DIR__ . '/src/Form/Privat24Form.php',
  'Privat24\Helper\Prvat24Helper'               => __DIR__ . '/src/Helper/Privat24Helper.php',
);
