<?php
// Generated by ZF2's ./bin/templatemap_generator.php
return array(
    'privat24/privat24/pay'            => __DIR__ . '/view/form/pay.phtml',
    'privat24/privat24/result'         => __DIR__ . '/view/form/result.phtml',
);
